"""Render the final next-100 list to markdown and a simple HTML page."""
from __future__ import annotations

import argparse
from pathlib import Path

from jinja2 import Template

from .common import DATA, OUTPUT, env, lib_data, lib_output, library_key, load_json

LIBBY_LINK = "https://libbyapp.com/library/{lib}/everything/page-1/{tid}"

MD = """# Your Next 100 Reads — from {{ lib }} (Libby)

Curated against {{ n_reads }} books you've already read. All titles below are available in this library's digital collection.

{% for theme in themes %}
## {{ loop.index }}. {{ theme.name }}

_{{ theme.blurb }}_

{% for p in theme.picks %}
- **[{{ p.title }}]({{ libby(p.titleId) }})** — {{ p.author }}{% if p.isAvailable %} · _available now_{% elif p.holdsCount %} · _holds: {{ p.holdsCount }}_{% endif %}
  - {{ p.why }}
{% endfor %}
{% endfor %}

---
_Generated by the personal book recommender pipeline. Re-run anytime as the catalog changes._
"""

HTML = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Your Next 100 Reads</title>
<style>
  :root { color-scheme: light dark; }
  body { font: 16px/1.55 -apple-system, system-ui, sans-serif; max-width: 880px; margin: 2rem auto; padding: 0 1rem; }
  h1 { margin-bottom: .25rem; }
  h2 { margin-top: 2rem; border-bottom: 1px solid #8884; padding-bottom: .25rem; }
  .pick { display: flex; gap: 1rem; padding: .75rem 0; border-bottom: 1px solid #8882; }
  .pick img { width: 64px; height: 96px; object-fit: cover; border-radius: 4px; flex: 0 0 auto; background: #8883; }
  .pick .meta { flex: 1; }
  .pick a { font-weight: 600; }
  .pick .why { color: #888; font-size: .95em; margin-top: .25rem; }
  .badge { display: inline-block; font-size: .75em; padding: 1px 6px; border-radius: 4px; background: #4caf50; color: white; margin-left: .5rem; }
  .badge.wait { background: #ff9800; }
  .blurb { font-style: italic; color: #888; }
</style>
</head>
<body>
<h1>Your Next 100 Reads</h1>
<p>From <b>{{ lib }}</b>'s Libby collection. Curated against {{ n_reads }} books you've read.</p>

{% for theme in themes %}
<h2>{{ loop.index }}. {{ theme.name }}</h2>
<p class="blurb">{{ theme.blurb }}</p>
{% for p in theme.picks %}
<div class="pick">
  {% if p.coverUrl %}<img src="{{ p.coverUrl }}" alt="">{% else %}<div style="width:64px;height:96px;background:#8883;border-radius:4px"></div>{% endif %}
  <div class="meta">
    <a href="{{ libby(p.titleId) }}" target="_blank">{{ p.title }}</a>
    <span>— {{ p.author }}</span>
    {% if p.isAvailable %}<span class="badge">available</span>
    {% elif p.holdsCount %}<span class="badge wait">{{ p.holdsCount }} holds</span>
    {% endif %}
    <div class="why">{{ p.why }}</div>
  </div>
</div>
{% endfor %}
{% endfor %}
</body>
</html>
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--library", "-l", help="OverDrive library key")
    ap.add_argument("--input", type=Path, default=None, help="Override picks JSON path")
    ap.add_argument("--md", type=Path, default=None, help="Override markdown output path")
    ap.add_argument("--html", type=Path, default=None, help="Override HTML output path")
    args = ap.parse_args()

    lib = library_key(args.library)
    src = args.input or (lib_data(lib) / "next_100.json")
    md_path = args.md or (lib_output(lib) / "next_100.md")
    html_path = args.html or (lib_output(lib) / "next_100.html")

    data = load_json(src) or {}
    themes = data.get("themes", [])
    reads = load_json(DATA / "read.json") or []

    def libby(tid: str) -> str:
        return LIBBY_LINK.format(lib=lib, tid=tid)

    md_path.write_text(
        Template(MD).render(themes=themes, n_reads=len(reads), libby=libby, lib=lib)
    )
    html_path.write_text(
        Template(HTML).render(themes=themes, n_reads=len(reads), libby=libby, lib=lib)
    )
    n = sum(len(t.get("picks", [])) for t in themes)
    print(f"Wrote {md_path} and {html_path} ({n} picks across {len(themes)} themes)")


if __name__ == "__main__":
    main()
